[platformio]
src_dir = .

[env:xiao_esp32c6]
; pioarduino — форк espressif32 с поддержкой Arduino на ESP32-C6/H2
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino

; End Device: таблица с zb_storage + большой app-слот под прошивку (~1.5 MB)
board_build.partitions = zigbee_zczr_4mb.csv
board_build.sdkconfig_options =
    CONFIG_ZB_ENABLED=y
    CONFIG_ZB_ZED=y

build_flags =
    -DZIGBEE_MODE_ED
    -DCORE_DEBUG_LEVEL=0

extra_scripts = pre:extra_script.py

build_src_filter = +<*> -<cmake-build-debug/> -<.pio/>

lib_deps =
    bblanchon/ArduinoJson@^6.21.0

monitor_speed = 115200
monitor_dtr = 1
